# Swagger File for DurkaDurka API
# It kind of works, but i haven't figured it all out yet..*
#
swagger: '2.0'

info:
  version: "1.0.0"
  title: DurkaDurka

host: dev.jkbworld.com:5000

paths:
  /ddapi/v1.0/durkadurka:
    get:
      description: Gets `DurkaDurka` objects.
      produces:
      - application/json
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfDurkaDurkas
            type: array
            items:
              title: DurkaDurka
              type: object
              properties:
                id:
                  type: integer
                durka1:
                  type: string
                durka2:
                  type: string
  /ddapi/v1.0/durkadurka/{id}:
    post:
      description: Adds a new DurkaDurka!
      produces:
      - application/json
      parameters:
        name: id
        in: path
        description: ID of the DurkaDurka
        required: True
      responses:
        200:
          description: Successful Response
        400:
          description: Failed Response
        500:
          description: Really Bad Response
